/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAventuraRouteImport } from './routes/_authenticated/aventura'
import { Route as AuthenticatedDocenteRouteImport } from './routes/_authenticated/docente'
import { Route as AuthenticatedHeroeRouteImport } from './routes/_authenticated/heroe'
import { Route as AuthenticatedPersonalizarRouteImport } from './routes/_authenticated/personalizar'
import { Route as AuthenticatedMisionMisionIdRouteImport } from './routes/_authenticated/mision.$misionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAventuraRoute = AuthenticatedAventuraRouteImport.update({
  id: '/aventura',
  path: '/aventura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocenteRoute = AuthenticatedDocenteRouteImport.update({
  id: '/docente',
  path: '/docente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHeroeRoute = AuthenticatedHeroeRouteImport.update({
  id: '/heroe',
  path: '/heroe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonalizarRoute =
  AuthenticatedPersonalizarRouteImport.update({
    id: '/personalizar',
    path: '/personalizar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMisionMisionIdRoute =
  AuthenticatedMisionMisionIdRouteImport.update({
    id: '/mision/$misionId',
    path: '/mision/$misionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aventura': typeof AuthenticatedAventuraRoute
  '/docente': typeof AuthenticatedDocenteRoute
  '/heroe': typeof AuthenticatedHeroeRoute
  '/personalizar': typeof AuthenticatedPersonalizarRoute
  '/mision/$misionId': typeof AuthenticatedMisionMisionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aventura': typeof AuthenticatedAventuraRoute
  '/docente': typeof AuthenticatedDocenteRoute
  '/heroe': typeof AuthenticatedHeroeRoute
  '/personalizar': typeof AuthenticatedPersonalizarRoute
  '/mision/$misionId': typeof AuthenticatedMisionMisionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/aventura': typeof AuthenticatedAventuraRoute
  '/_authenticated/docente': typeof AuthenticatedDocenteRoute
  '/_authenticated/heroe': typeof AuthenticatedHeroeRoute
  '/_authenticated/personalizar': typeof AuthenticatedPersonalizarRoute
  '/_authenticated/mision/$misionId': typeof AuthenticatedMisionMisionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/aventura'
    | '/docente'
    | '/heroe'
    | '/personalizar'
    | '/mision/$misionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/aventura'
    | '/docente'
    | '/heroe'
    | '/personalizar'
    | '/mision/$misionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/aventura'
    | '/_authenticated/docente'
    | '/_authenticated/heroe'
    | '/_authenticated/personalizar'
    | '/_authenticated/mision/$misionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/aventura': {
      id: '/_authenticated/aventura'
      path: '/aventura'
      fullPath: '/aventura'
      preLoaderRoute: typeof AuthenticatedAventuraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docente': {
      id: '/_authenticated/docente'
      path: '/docente'
      fullPath: '/docente'
      preLoaderRoute: typeof AuthenticatedDocenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/heroe': {
      id: '/_authenticated/heroe'
      path: '/heroe'
      fullPath: '/heroe'
      preLoaderRoute: typeof AuthenticatedHeroeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personalizar': {
      id: '/_authenticated/personalizar'
      path: '/personalizar'
      fullPath: '/personalizar'
      preLoaderRoute: typeof AuthenticatedPersonalizarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mision/$misionId': {
      id: '/_authenticated/mision/$misionId'
      path: '/mision/$misionId'
      fullPath: '/mision/$misionId'
      preLoaderRoute: typeof AuthenticatedMisionMisionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAventuraRoute: typeof AuthenticatedAventuraRoute
  AuthenticatedDocenteRoute: typeof AuthenticatedDocenteRoute
  AuthenticatedHeroeRoute: typeof AuthenticatedHeroeRoute
  AuthenticatedPersonalizarRoute: typeof AuthenticatedPersonalizarRoute
  AuthenticatedMisionMisionIdRoute: typeof AuthenticatedMisionMisionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAventuraRoute: AuthenticatedAventuraRoute,
  AuthenticatedDocenteRoute: AuthenticatedDocenteRoute,
  AuthenticatedHeroeRoute: AuthenticatedHeroeRoute,
  AuthenticatedPersonalizarRoute: AuthenticatedPersonalizarRoute,
  AuthenticatedMisionMisionIdRoute: AuthenticatedMisionMisionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
